
replicaCount: 2

image:
  repository: denis78/compose-main
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: my-app-service
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer

ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: nginx
  hosts:
    - host: mycluster.k8s-9.sa
      paths:
        - path: "/"
          backend:
            serviceName: app
            servicePort: 9000
        - path: "/sonar"
          backend:
            serviceName: sonar
            servicePort: 9001
        - path: "/radar"
          backend:
            serviceName: radar
            servicePort: 9002
  tls: []
resources:
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 200m
    memory: 200Mi

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
