
replicaCount: 2

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: my-app-service
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer

ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: nginx
  hosts:
    - host: mycluster.k8s-9.sa

  tls: []
resources:
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 200m
    memory: 200Mi

pullPolicy: IfNotPresent

microservices:
  - name: app
    port: 80
    targetPort: 9000
    path: "/"
    imege: "denis78/compose-main:latest"
  - name: sonar
    port: 9001
    targetPort: 9001
    path: "/sonar"
    imege: "denis78/compose-first:latest"
  - name: radar
    port: 9002
    targetPort: 9002
    path: "/radar"
    imege: "denis78/compose-second:latest"

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
