apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
      name: app
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: sonar
    - port: 9002
      targetPort: 9002
      protocol: TCP
      name: radar
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
