apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.microservices }}
      - port: {{ .port }}
        targetPort: {{ .targetPort }}
        protocol: TCP
        name: {{ .name }}
    {{- end }}
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
